### ISSUE TITLE
Removes all code

### ISSUE THREAD

**Issue by whitequark** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#18]
I'm not sure what happens exactly but when I press Ctrl+Alt+B on a file containing, say:
```
[1, 2]
```
everything just gets removed. There are no messages in the console.

**Comment by whitequark** [comment]
The config file is set up for chruby as follows:
```
  // the command to run your ruby, again this is setup for rbenv
  // if you've installed Ruby without any managers, this would just be "ruby"
  "ruby_command": "/opt/rubies/ruby-2.2.4/bin/ruby",


  // environment variables to set before running
  "environment_variables": {
    // for bootstrapping rbenv
    // if you manage your versions differently, you'll have to figure out how your manager works
    "LANG": "en_US.UTF-8",
    "RUBY_ROOT": "/opt/rubies/ruby-2.2.4",
    "GEM_HOME": "/home/whitequark/.gem/ruby/2.2.4",
    "GEM_PATH": "/home/whitequark/.gem/ruby/2.2.4:/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0",
    "GEM_ROOT": "/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0"
  },
```

**Comment by JoshCheek** [comment]
See if this works:

```sh
$ /opt/rubies/ruby-2.2.4/bin/ruby -S seeing_is_believing -e '1 + 1'
```

If not, uninstall SiB and try installing again with `gem install seeing_is_believing -v 3.0.0.beta.7` a conjunction of stupidity and laziness means I haven't released it out of beta, so it installs the broken v2 by default.

Most of my integration effort has gone to Atom, so the feedback for sublime is just substandard, but you can get a console with Control backtick where it probably prints an error message. If the above doesn't fix it, check if there's something printed there.

**Comment by whitequark** [comment]
That doesn't work:
```
program-without-annotations:1:1: error: cannot insert "$SiB.record_result(1, ("
program-without-annotations:1: 1 + 1
program-without-annotations:1:      
program-without-annotations:1:1: note: clobbered by: insert "begin; $SiB.number_of_captures = Float::INFINITY; "
program-without-annotations:1: 1 + 1
program-without-annotations:1:      
Parser::ClobberingError
Parser::Source::Rewriter detected clobbering

/home/whitequark/.gem/ruby/2.2.4/gems/parser-2.3.0.3/lib/parser/source/rewriter.rb:387:in `raise_clobber_error'
/home/whitequark/.gem/ruby/2.2.4/gems/parser-2.3.0.3/lib/parser/source/rewriter.rb:209:in `append'
/home/whitequark/.gem/ruby/2.2.4/gems/parser-2.3.0.3/lib/parser/source/rewriter.rb:64:in `insert_before'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:36:in `block in call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:35:in `each'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:35:in `call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:11:in `call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:52:in `program_that_will_record_expressions'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:34:in `call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:15:in `call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary/add_annotations.rb:29:in `initialize'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `new'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `annotator'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:114:in `evaluate_program'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:45:in `call'
/home/whitequark/.gem/ruby/2.2.4/gems/seeing_is_believing-2.2.0/bin/seeing_is_believing:6:in `<top (required)>'
/home/whitequark/.gem/ruby/2.2.4/bin/seeing_is_believing:23:in `load'
/home/whitequark/.gem/ruby/2.2.4/bin/seeing_is_believing:23:in `<main>'
```
... on either 2.x on the 3.x beta you have specified. There were also no messages in the console.

Anyway, I wasn't able to use SiB for what I wanted, so I'm no longer very interested in this.

**Comment by JoshCheek** [comment]
It's loading the old SiB.

```sh
$  gem uninstall seeing_is_believing -v 2.2.0
```

**Comment by JoshCheek** [comment]
Curiousity: What were you going to use it for?

**Comment by JoshCheek** [comment]
Closing this as I just released v3.0 so this should be fixed.

---

If piping through irb was useful, consider these ways of using SiB:

```ruby
$ cat program.rb
5.times do |i|
  i
end
2 + 3
```

Access the line results as a JSON data structure:

```json
$ cat program.rb | seeing_is_believing --json
{"stdout":"","stderr":"","exitstatus":0,"exception":null,"lines":{"1":["5"],"2":["0","1","2","3","4"],"3":["5"],"4":["5"]}}
```

Stream the results as they become available, each line is a JSON tuple of type and data

```json
$ cat program.rb | seeing_is_believing --stream
["ruby_version",{"value":"2.3.1"}]
["sib_version",{"value":"3.0.0"}]
["filename",{"value":"/var/folders/7g/mbft22555w3_2nqs_h1kbglw0000gn/T/seeing_is_believing_temp_dir20161008-63298-1yjm0ry/program.rb"}]
["num_lines",{"value":4}]
["max_line_captures",{"value":-1,"is_infinity":true}]
["line_result",{"type":"inspect","line_number":1,"inspected":"5"}]
["line_result",{"type":"inspect","line_number":2,"inspected":"0"}]
["line_result",{"type":"inspect","line_number":2,"inspected":"1"}]
["line_result",{"type":"inspect","line_number":2,"inspected":"2"}]
["line_result",{"type":"inspect","line_number":2,"inspected":"3"}]
["line_result",{"type":"inspect","line_number":2,"inspected":"4"}]
["line_result",{"type":"inspect","line_number":3,"inspected":"5"}]
["line_result",{"type":"inspect","line_number":4,"inspected":"5"}]
["event_stream_closed",{"side":"producer"}]
["stdout_closed",{"side":"producer"}]
["stderr_closed",{"side":"producer"}]
["exitstatus",{"value":0}]
["finished",{}]
```

Compare to irb:

```ruby
$ cat program.rb | irb
Switch to inspect mode.
5.times do |i|
  i
end
5
2 + 3
5
``

**Comment by whitequark** [comment]
It was for this issue: https://github.com/whitequark/parser/issues/312#issuecomment-252407424

**Comment by JoshCheek** [comment]
Your solution worked well. This is the equivalent in SiB:

```ruby
$ curl -s http://hastebin.com/raw/ucewudixew | ruby -lpe 'gsub(/;.*$/,"") && ~/lambda/ && !(eval $_ rescue nil) && $_=$_.ljust(37)+"rescue $!.message"' | seeing_is_believing
proc{|a,| [a]}.call(1)            # => [1]
proc{|a,| [a]}.call(1, 2)         # => [1]
proc{|a,| [a]}.call(1, 2, 3)      # => [1]
proc{|a,b| [a,b]}.call(1)         # => [1, nil]
proc{|a,b| [a,b]}.call(1, 2)      # => [1, 2]
proc{|a,b| [a,b]}.call(1, 2, 3)   # => [1, 2]
proc{|a,b,| [a,b]}.call(1)        # => [1, nil]
proc{|a,b,| [a,b]}.call(1, 2)     # => [1, 2]
proc{|a,b,| [a,b]}.call(1, 2, 3)  # => [1, 2]

a, = 1          # => 1
a, = 1, 2       # => [1, 2]
a, = 1, 2, 3    # => [1, 2, 3]
a,b = 1         # => 1
a,b = 1, 2      # => [1, 2]
a,b = 1, 2, 3   # => [1, 2, 3]
a,b, = 1        # => 1
a,b, = 1, 2     # => [1, 2]
a,b, = 1, 2, 3  # => [1, 2, 3]

proc{|a,| [a]}.call([1])            # => [1]
proc{|a,| [a]}.call([1, 2])         # => [1]
proc{|a,| [a]}.call([1, 2, 3])      # => [1]
proc{|a,b| [a,b]}.call([1])         # => [1, nil]
proc{|a,b| [a,b]}.call([1, 2])      # => [1, 2]
proc{|a,b| [a,b]}.call([1, 2, 3])   # => [1, 2]
proc{|a,b,| [a,b]}.call([1])        # => [1, nil]
proc{|a,b,| [a,b]}.call([1, 2])     # => [1, 2]
proc{|a,b,| [a,b]}.call([1, 2, 3])  # => [1, 2]

a, = [1]          # => [1]
a, = [1, 2]       # => [1, 2]
a, = [1, 2, 3]    # => [1, 2, 3]
a,b = [1]         # => [1]
a,b = [1, 2]      # => [1, 2]
a,b = [1, 2, 3]   # => [1, 2, 3]
a,b, = [1]        # => [1]
a,b, = [1, 2]     # => [1, 2]
a,b, = [1, 2, 3]  # => [1, 2, 3]

lambda{|a,| [a]}.call(1)                                # => [1]
lambda{|a,| [a]}.call(1, 2)          rescue $!.message  # => "wrong number of arguments (given 2, expected 1)"
lambda{|a,| [a]}.call(1, 2, 3)       rescue $!.message  # => "wrong number of arguments (given 3, expected 1)"
lambda{|a,b| [a,b]}.call(1)          rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b| [a,b]}.call(1, 2)                          # => [1, 2]
lambda{|a,b| [a,b]}.call(1, 2, 3)    rescue $!.message  # => "wrong number of arguments (given 3, expected 2)"
lambda{|a,b,| [a,b]}.call(1)         rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b,| [a,b]}.call(1, 2)                         # => [1, 2]
lambda{|a,b,| [a,b]}.call(1, 2, 3)   rescue $!.message  # => "wrong number of arguments (given 3, expected 2)"

lambda{|a,| [a]}.call([1])                              # => [[1]]
lambda{|a,| [a]}.call([1, 2])                           # => [[1, 2]]
lambda{|a,| [a]}.call([1, 2, 3])                        # => [[1, 2, 3]]
lambda{|a,b| [a,b]}.call([1])        rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b| [a,b]}.call([1, 2])     rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b| [a,b]}.call([1, 2, 3])  rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b,| [a,b]}.call([1])       rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b,| [a,b]}.call([1, 2])    rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"
lambda{|a,b,| [a,b]}.call([1, 2, 3]) rescue $!.message  # => "wrong number of arguments (given 1, expected 2)"

proc{|a| [a]}.call(1)        # => [1]
proc{|a| [a]}.call(1, 2)     # => [1]
proc{|a| [a]}.call(1, 2, 3)  # => [1]

proc{|a| [a]}.call([1])        # => [[1]]
proc{|a| [a]}.call([1, 2])     # => [[1, 2]]
proc{|a| [a]}.call([1, 2, 3])  # => [[1, 2, 3]]
```
